development:
  adapter: mysql
  database: blogjax_dev
  username: root
  password:
  host: localhost
  port: 3306

test:
  adapter: mysql
  database: blogjax_test
  username: root
  password:
  host: localhost
  port: 3306

production:
  development
